#!/bin/sh -ex

DB_PASS=$(mcookie)
REMOTE_USER=remote

# configure mysql to listen on all interfacesq
sed -i "s|^bind-address|#bind-address|" /etc/mysql/mariadb.conf.d/50-server.cnf

# generate SSL certs for MySQL remote connections (rerun on firstboot)
/usr/lib/inithooks/firstboot.d/20regen-mysql-certs

# allow remote connections & enable SSL by default
service mysql start
mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO '$REMOTE_USER'@'%' IDENTIFIED BY '$DB_PASS';"
mysql -u root -e "FLUSH PRIVILEGES;"
turnkey-mysql-ssl enable
service mysql stop

# enable tklcp site
sed -Ei "s|^(server.document-root.*=).*|\1 \"/var/www\"|" /etc/lighttpd/lighttpd.conf
lighty-enable-mod tklcp || true
