#!/bin/sh -e

# Configure lighttpd for phpmyadmin
cat > /etc/phpmyadmin/lighttpd.conf <<EOF
\$HTTP["url"] =~ "^/" {
    server.document-root = "/usr/share/phpmyadmin"
}

\$HTTP["url"] =~ "^/scripts/setup.php" {
    url.access-deny = ( "" )
}
EOF

ln -s /etc/phpmyadmin/lighttpd.conf /etc/lighttpd/conf-available/50-phpmyadmin.conf
lighty-enable-mod fastcgi
lighty-enable-mod phpmyadmin

